### PR TITLE
speedtest-cli

### PR DESCRIPTION
**Pull request by JesseZhuang**
interesting http tool working with speedtest.net API.

### CODE REVIEW

**Comment by ywang0701** [comment]
http://www.speedtest.net/  is very impressive on measuring upload/download speed and give you your IP, location, and internet provider. My download/upload speed is 58.43/6.06 Mbps. The UI with a global map makes the tool more user friendly. 

This is a great tool to keep in the tool box and a clean code to learn from.

**Comment by JesseZhuang** [comment]
@ywang0701 exactly, [look here](https://github.com/InCodeLearning/Python2/issues/4). I will assign this to both of us.

**Comment by ywang0701** [comment]
The code runs on my PC without any issue.  Here are the execution steps:
0. Test env: window 10, Python2.7
1. git clone
2. git checkout jesse
3. cd to Python2\internet
4. python speedtest-cli  The test results are displayed below

image

**Comment by ywang0701** [comment]
@JesseZhuang  The code works like a charm. I propose to push this PR to dev branch and create a master-PR. Then, you can push it to master branch.

**Comment by ywang0701** [comment]
FYI, I don't have the right to merge this PR.  So, either you give me the merge-permission or you can merge this PR to dev. Then you can create its master-PR and execute the merge. Thx -Yong

image

**Comment by JesseZhuang** [comment]
We will first discuss all PRs on weekly meeting before we merge them. That's the workflow.

**Pull request merged**
